In [1]:
import numpy as np

In [16]:
arry = np.arange(25)

In [17]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arry.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
np.resize(arry,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
arr1 = arry.reshape(5,5)
arr2 = np.resize(arry,(3,2))
print("reshape:",arr1)
print("resize:",arr2)
print("=================")
arr1[3][1] = 99
print("reshape 2:",arr1)
print("reshape 3:",arry)
print("=================")
arr2[1][1] = 81
print("resize 2:",arr2)
print("resize 3:",arry)

reshape: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 99 17 18 19]
 [20 21 22 23 24]]
resize: [[0 1]
 [2 3]
 [4 5]]
reshape 2: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 99 17 18 19]
 [20 21 22 23 24]]
reshape 3: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 99 17 18 19 20 21 22 23
 24]
resize 2: [[ 0  1]
 [ 2 81]
 [ 4  5]]
resize 3: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 99 17 18 19 20 21 22 23
 24]


In [25]:
ranarr = np.random.randint(0,50,10)
ranarr

array([41, 42, 37, 17, 15, 34, 28, 15, 24, 48])

In [26]:
ranarr.max()

48

In [27]:
ranarr.min()

15

In [28]:
ranarr.argmax()

9

In [29]:
ranarr.argmin()

4

在NumPy中，可以使用不同的數據類型（dtype）來表示陣列中的元素。以下是一些常見的dtype類型：

1. **int**：整數，可以是int8、int16、int32、int64等不同大小的整數。
2. **uint**：無符號整數，可以是uint8、uint16、uint32、uint64等不同大小的無符號整數。
3. **float**：浮點數，可以是float16、float32、float64等不同精度的浮點數。
4. **complex**：複數，可以是complex64、complex128等不同精度的複數。
5. **bool**：布爾值，表示True或False。
6. **object**：Python對象，可以是任何Python對象。
7. **string_**：字串，固定大小的字串。
8. **unicode_**：Unicode字串，固定大小的Unicode字串。

除了以上列出的類型外，還有其他一些特殊的類型，這取決於具體的應用場景和需要。您可以通過使用`np.dtype`類來創建自定義的dtype，以滿足特定的數據需求。

In [33]:
import numpy as np
arry = np.array([1.2,3.4,5.6])
print(arry,arry.dtype)
arr2 = arry.astype(np.int8)
print(arr2,arr2.dtype) 

[1.2 3.4 5.6] float64
[1 3 5] int8


In [35]:
import numpy as np
arr = np.arange(2,15)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr[8]

10

In [39]:
arr[1:5]

array([3, 4, 5, 6])

In [41]:
arr[1:5] = 100

In [42]:
arr

array([  2, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,  14])

In [43]:
arr = np.arange(2,15)

In [44]:
arr2 = arr[0:6]
arr2

array([2, 3, 4, 5, 6, 7])

In [47]:
arr2[:] = 99

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

In [49]:
arr = np.arange(2,15)
arrCopy = arr.copy()
arrCopy[0:6] = 100

In [52]:
print(arr)
print(arrCopy)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[100 100 100 100 100 100   8   9  10  11  12  13  14]


## 課外電子書連接
 https://reurl.cc/laZY4j 

In [70]:
myList = list(range(1,21))
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [69]:
newList =  myList[1:6] #複製一份產生新的List

In [57]:
newList[1] = 100
newList

[2, 100, 4, 5, 6]

In [58]:
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [71]:
import numpy as np
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[1]

array([20, 25, 30])

In [74]:
arr_2d[1,0]

20

In [76]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[2]

array([35, 40, 45])

In [80]:
arr_2d[2,0:2]

array([35, 40])

## 條件選擇

這是一個非常基礎的概念，稍後將直接應用於 pandas，請確保你理解這部分！

我們來簡要介紹如何使用括號進行基於比較運算符的選擇。

In [81]:
arr  = np.arange(1,11)

In [84]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
bool_arr = arr > 4

In [85]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## 算術運算

你可以輕鬆地進行*陣列與陣列*的算術運算，或者*標量與陣列*的算術運算。讓我們來看一些例子：

In [87]:
import numpy as np

In [88]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [92]:
arr / arr

C:\Users\xvpow\AppData\Local\Temp\ipykernel_19384\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## 通用陣列函數

NumPy 提供了許多[通用陣列函數](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)，或稱為 <em>ufuncs</em>（universal functions），它們本質上是可以應用於整個陣列的數學運算。讓我們來展示一些常見的通用函數：

1. **np.add** - 對陣列中的元素進行加法運算。
2. **np.subtract** - 對陣列中的元素進行減法運算。
3. **np.multiply** - 對陣列中的元素進行乘法運算。
4. **np.divide** - 對陣列中的元素進行除法運算。
5. **np.sqrt** - 計算陣列中每個元素的平方根。
6. **np.exp** - 計算 e 的指數，應用於陣列中的每個元素。
7. **np.log** - 計算陣列中每個元素的自然對數。
8. **np.sin**, **np.cos**, **np.tan** - 分別計算陣列中元素的正弦、餘弦和正切值。

這些函數可以對整個陣列進行快速和有效的元素級運算，使得數據處理更加方便和高效。

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [96]:
np.log(arr)

C:\Users\xvpow\AppData\Local\Temp\ipykernel_19384\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])


In [99]:
arr = np.arange(1,13)
arr_2d = arr.reshape(3,4)

In [ ]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
arr_2d[0][0] +arr_2d[0][1] +arr_2d[0][2] + arr_2d[0][3]


10

In [110]:
arr_2d[1][0] +arr_2d[1][1] +arr_2d[1][2] + arr_2d[1][3]

26

In [111]:
arr_2d[2][0] +arr_2d[2][1] +arr_2d[2][2] + arr_2d[2][3]

42

In [101]:
arr_2d.shape

(3, 4)

In [106]:
arr_2d.sum()

78

In [107]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [108]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [112]:
import numpy as np

## 創建一個包含10個零的陣列
```python
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```


In [115]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 創建一個包含10個1的陣列

```python
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

```

In [117]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## 產生10個5的陣列

```python
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

```

In [118]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 產生以下數值的陣列
```python
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```

In [119]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##  要創建一個3x3矩陣，其中包含從0到8的值
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

In [122]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 要創建一個3x3的單位矩陣（identity matrix）
```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##  要使用 NumPy 生成一個介於0和1之間的隨機數

In [200]:
np.random.rand(1)

array([0.42462832])

## 要使用 NumPy 生成一個包含25個從標準正態分布（平均值為0，標準差為1的正態分布）抽樣的隨機數陣列

In [201]:
np.random.randn(25)

array([-0.3493931 , -0.33438884,  0.09899774, -1.31262306,  1.74963338,
        0.31252124, -0.43205659,  0.49319968, -0.08776784,  0.52553618,
        0.02105407,  0.18020021,  0.56726137, -0.35019612, -1.48694953,
       -0.94372455,  0.17051285, -1.7931617 ,  0.11353258,  1.13753747,
        0.73836977, -0.57173588, -1.76643569,  1.68803352, -1.17008224])

##  要創建一個包含從0到1之間20個等距點的陣列

```python
array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

```

In [203]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## 幫我產生以下的陣列
```ptyhon
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```


In [206]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 根據以下輸出完成功能
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [207]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## 根據以下輸出完成功能
20

#### 根據以下輸出完成功能
```python
array([[ 2],
       [ 7],
       [12]])
```

```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```